### ISSUE TITLE
We need to update translations

### ISSUE THREAD

**Issue by RDMurray** [soundscape-community/soundscape#104]
Someone needs to look into translations again. we did have weblate set up last year, but it deleted some existing strings, see #43 .

**Comment by RDMurray** [comment]
@bramd could you please try clearing the error on weblate and hopefully it will start working again?

Also is it possible to rename the weblate project and update the repo URL?

**Comment by RDMurray** [comment]
I think we should get moving on this as soon as possible since the translations are quite out of date now.

Should we continue with Weblate, or switch to another localization system? We could create a new project on Weblate for Soundscape Community. The current one is still Openscape and is blocked because of merge conflicts.
We could also use Crowdin, which seems to be very popular and is free for OSS projects.

I can't comment on which is better from the translators' point of view. 

Weblate doesn't currently support XLIFF 2.0, which apparently is the future preferred format for Xcode projects, whereas Crowdin does. I can't see any immediate need to switch to XLIFF, so it maybe doesn't matter.


Any thoughts on which is the best option?

**Comment by steinbro** [comment]
I say use whichever one is more screenreader-friendly for translators :)

**Comment by RDMurray** [comment]
Weblate appears to be reasonably screen reader accessible so I suggest we stick with it for now. We either need to get access to the existing openscape project and fix it or create a new project on Weblate for Soundscape Community.

**Comment by bramd** [comment]
I set up the Weblate project at the time. I'll try to get it updated again. Please create a Weblate account and reply here if you want admin access to the project as well, I would prefer to be not the only one with those rights.

It seems Weblate has a CAPTCHA on signup now, this might be a barrier to entry for new translaters and could be a reason to switch. I'm open to switching to something else if it has clear benefits.

**Comment by RDMurray** [comment]
Oops, I created a new project on Weblate but forgot to comment here. I can delete that now though.

My user is `rob at mur.org.uk`

There is also a user for soundscape's gmail `community.soundscape at gmail.com`.

I managed the captcha with an nvda addon, but maybe I should request that they make the captcha accessible. for me it was "what is 5 + 9" but the plus sign was invisible to NVDA. I'm sure they could fix that fairly easily.

**Comment by bramd** [comment]
@RDMurray I just added you and the Soundscape Gmail to the project.

I think they hide the + on purpose to make solving the CAPTCHA harder, but with current OCR/AI technology I doubt that it will help much.

I just translated some new strings in Dutch to see if the process is working. I have no idea why some strings got deleted earlier, might be because of the Openscape to Soundscape rename. I hope this will not happen again.

**Comment by bramd** [comment]
I saw some unexpected changes in Finish, Swedish and Norwegian, but it seems that's only re-adding a newline at the end of the file.

**Comment by RDMurray** [comment]
Yep I saw that. 

I'll delete the other project now.

There are a bunch of suggestions for Norwegian. I am tempted to just accept suggestions even though I can't check them since they were presumably written by a native speaker. What do you think?

**Comment by bramd** [comment]
> Yep I saw that.
> 
> I'll delete the other project now.
> 
> There are a bunch of suggestions for Norwegian. I am tempted to just accept suggestions even though I can't check them since they were presumably written by a native speaker. What do you think?

Ideally I would have them checked by someone who can at least understand the language, but I don't know anybody. It seems Weblate also gives suggestions sometimes, for example if a translation does not end with the same punctuation as the original it will suggest to change that. So may be not all suggestions are from humans?

I checked some suggestions and some seem to suggest exactly what is already the current translation, I don't know what happened there.
