### ISSUE TITLE
Update Help content for Soundscape Community app

### ISSUE THREAD

**Issue by jchudge** [soundscape-community/soundscape#114]
Feedback and attached file from user feedback:
Proposed changes to the help documentation, including the "callouts" fix. 
Recommendation to merge these changes after the "Settings" screen gets reorganized, and the "Audio Beacon" menu gets moved out of the "General Settings" menu.
[Soundscape Help Documentation Proposed Changes, Revised.txt](https://github.com/user-attachments/files/17435425/Soundscape.Help.Documentation.Proposed.Changes.Revised.txt)

**Comment by RDMurray** [comment]
If any non-developers want to take this on, the translation system at [Weblate](https://hosted.weblate.org/projects/soundscape/) can also be used to edit any English text in the app. 

You should make the same changes to "English (United Kingdom)".

**Comment by ryanThomas21** [comment]
I made a pull request using the changes you advised for both the US and UK English documentation and fixed other grammar mistakes I saw.

**Comment by steinbro** [comment]
Thanks!
