### ISSUE TITLE
Places Nearby

### ISSUE THREAD

**Issue by steinbro** [soundscape-community/soundscape#13]
The list of Places Nearby is currently populated, but not with the same quality of results as the prior app (why would I want to locate nearby crosswalks?) I'm guessing this is because it previously used the search provider (Bing) to get information about nearby points of interest, and it's currently falling back on the callout data from the tile server, which has less interesting places. So, linking a search provider is not as easy as just populating the results when the serch box is typed into.

**Comment by LegendusMaximus** [comment]
You can also only filter by "All places" or "Public transport", whereas in the original app you could filter by other categories (e.g. Food and drink, ATM's).

**Comment by steinbro** [comment]
@LegendusMaximus Yeah, those categorizations almost certainly came from Bing -- those aren't categories OpenStreetMap uses.

**Comment by steinbro** [comment]
Closing as duplicative of #82.
