### ISSUE TITLE
Import/export markers and routes

### ISSUE THREAD

**Issue by steinbro** [soundscape-community/soundscape#17]
@bramd suggested in the chat that one way to export markers from Soundscape is to add them to a route, then export as a JSON file. Can we add functionality to import these into Openscape?

See also: https://github.com/microsoft/soundscape/issues/17#issuecomment-1597608859

**Comment by RDMurray** [comment]
I can confirm that this method works for soundscape. I shared a route with all my markers by email, deleted all my soundscape data, and then opened the .soundscape file from the email. It restored all the markers.

The only reason the same thing doesn't work with openscape is that the file extension changed to `.openscape`, probably as a result of find/replace.

I propose that we revert the file extension to `.soundscape` to enable compatibility with soundscape and soundscape for everyone in the future.

**Comment by RDMurray** [comment]
it's set in [info.plist line 182](https://github.com/openscape-community/openscape/blob/mapkit-search/apps/ios/GuideDogs/Assets/PropertyLists/Info.plist#L182)

**Comment by steinbro** [comment]
Pull request? :)

**Comment by RDMurray** [comment]
It turns out not to be as straight forward as I thought. To export a UTTypeIdentifier you have to be the authoritative source of information about the file type. Creating a new UTTypeIdentifier with the .soundscape extension seems to override the original soundscape one, preventing soundscape from opening it's own route files. If we import the UTTypeIdentifier from soundscape, that will presumably only work while soundscape is still installed, although I haven't tested this. Does anyone know the correct solution?

**Comment by towebo** [comment]
An app can register to handle a certain file extention and if an user taps on a file with that extention a list of alternatives will be presented. If Openscape registers for both .soundscape and .openscape it will be able to handle both of them while Soundscape only wakes up if it's a .soundscape file.

**Comment by steinbro** [comment]
@RDMurray I think breaking old Soundscape isn't problematic, since it's being deprecated and Openscape is meant to replace it.

@Oliver2213 this issue is closed by dc585fc right?

**Comment by Oliver2213** [comment]
Yes. I added support for importing .soundscape files (with identifier soundscape.doc), as well as our own .openscape (io.openscape.doc). We export .openscape, but can import from the sunset app's files as well.
I've set our role for soundscape.doc to "Default", but Openscape still shows up only under the "more" option for me when I would hope it would be presented closer to the start.

**Comment by steinbro** [comment]
Closing since problems with the implementation are covered in separate issues, e.g. #49.
