### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by steinbro** [soundscape-community/soundscape#28]
As noted in #9, we're missing a set of regression tests to run on commits and pull requests. Based on [references in the build files](https://github.com/openscape-community/openscape/blob/d5bb4713e491571191af98e8aad6afc91fc1153e/apps/ios/GuideDogs.xcodeproj/xcshareddata/xcschemes/Openscape%20-%20Dogfood.xcscheme#L71), there are test cases that don't appear to have been included in the opensource release:
1. AutomaticCalloutsUnitTests
    a. testDestinationCallout
    b. testFilteredCategories
    c. testNearbyCallouts
3. GuideDogsUnitTests
    a. testAudioQueueingScenario6
    b. testFindTheWay
    c. testSettingsContextEnglishGBChange
    d. testSettingsContextEnglishGBFlipFlop
    e. testSoundQueueingScenario1
    f. testSoundQueueingScenario2
    g. testSoundQueueingScenario3
    h. testSoundQueueingScenario4
4. SharedContentUnitTests
    a. testParseGPX
5. TelemetryUnitTests
    a. testUpload

It's hard to tell from the names alone exactly what the tests did, but they do give some ideas as to what comprises a sufficient test suite.

**Comment by 2kai2kai2** [comment]
Hi! I'm working on pulling my tests from the old Soundscape for Everyone repo: https://github.com/2kai2kai2/soundscape
However, I've been having some new issues with building the cocoapods dependencies so that should probably be fixed before merging.

**Comment by steinbro** [comment]
@2kai2kai2 Thanks! Just a couple of days ago, I copied your ios-tests.yml GitHub Action into this repo in the hopes it would just work, but of course it didn't. Glad you're around to debug :)

**Comment by 2kai2kai2** [comment]
Update: I have a working test run, so once I make sure my changes towards issue #64 are working correctly I should be able to open a pull request, hopefully in the next week.
https://github.com/2kai2kai2/soundscape/actions/runs/6516399078/job/17699870775

**Comment by steinbro** [comment]
Merged in as part of #65.

**Comment by StevenAbrams** [comment]
Hi, Steven Abrams here (one of the testers that worked on Microsoft Soundscape). There is a question here about Unit Tests. I am assuming this refers to tests that the previous developers added into their code. Myself and Frazier were not involved with the creation or maintenance of the unit testing by developers. But we were totally responsible for regression testing and any other kind of manual testing once builds were released. I am not sure whether this helps or not. Please let me know how we can assist with any tests and we can take it from there. Thanks.

**Comment by steinbro** [comment]
@StevenAbrams Yep, this issue was about automated unit tests. We now have a sizable collection of them thanks to @2kai2kai2 that span geometry calculations, the audio engine, file parsing, and others. I'm not sure how exhaustive the unit test suite at Microsoft was, since I can only infer from the residual test names what they actually covered. But I think we're in good shape.
