### ISSUE TITLE
French/English text on the same screen 

### ISSUE THREAD

**Issue by jchudge** [soundscape-community/soundscape#43]
There are discrepancies in the text where both French and English text is appearing on screens. User has her language set to French but in the start up process there was a case of titles in French and text in English all the way through; sometimes one para was in French and the other one in English.
@StevenAbrams to repro and triage

**Comment by fraziercarr** [comment]
Commented this on Slack but adding here so it’s all in one place, I think this could be a potential cause:
If any of the English strings have changed, then if I remember correctly, those strings will display in English for other languages too. So changing one word in a paragraph could cause it to break. 
My guess would be changing “Microsoft Soundscape” to “Soundscape” could have broken some of the introduction paragraphs.

**Comment by fraziercarr** [comment]
Actually, ignore that. I’ve just looked in the app and there are a lot of strings that aren’t in French (or other languages), and it looks like they’re ones which haven’t changed

**Comment by steinbro** [comment]
I'm looking through our merge requests that came from our Weblate service, and they appear to have deleted lots and lots of strings in non-English translations for no apparent reason (e.g. #34).

I'm going to revert to the original files that came with the Microsoft open-source release. That'll revert some of @bramd's fixes for Dutch, if not others, but it will hopefully get us back to functional until we can figure out what went wrong with the integration.

**Comment by steinbro** [comment]
Closing as fixed (and duplicative of #50).
