### ISSUE TITLE
LOCALISATION: The CANCEL button appears in English for all languages

### ISSUE THREAD

**Issue by StevenAbrams** [soundscape-community/soundscape#52]
**Build: 1.0.0 (9)**

**Repro Steps:**
1. Change to any non-English language e.g., Japanese
2. Select the Search box at the top of the Home UI
3. View the Cancel button to the right of the search box on the next UI

**Expected Results:**
The "Cancel" button will be localised

**Actual Results:**
It appears to be in English for all non-English languages

**Comment by steinbro** [comment]
@fraziercarr is right: the language used for the cancel button is dependent on the global operating system language, not the app language. It's not what I would have expected, but I confirmed by changing the system language and seeing what happened.
