### ISSUE TITLE
LOCALISATION: When selecting App Setup from Help & Tutorials the user sees a UI called "first_launch.language"

### ISSUE THREAD

**Issue by StevenAbrams** [soundscape-community/soundscape#57]
**Build: 1.0.0 (9)**

**Repro Steps:**
1. Select the language settings in the app to non-English e.g., Italian
2. Go to the Soundscape Menu
3. Select Help & Tutorials
4. Select the 4th option down (App Setup)
5. Select the Get Started button

**Expected Results:**
The tutorial commences in the currently selected language

**Actual Results:**
A UI appears called "first_launch.language" as per the image. The user is prompted to select a language.

![IMG_3080](https://github.com/soundscape-community/soundscape/assets/6051244/c0dfd940-7ae1-4863-ad6d-3243fe7225ca)

**Comment by StevenAbrams** [comment]
@steinbro @Oliver2213 

Re-opening. Will verify the fix on the next build. Please confirm which build this fix will appear in.
Thanks

**Comment by Oliver2213** [comment]
@StevenAbrams build 10.

**Comment by StevenAbrams** [comment]
@Oliver2213 - Closing. Verified in 1.0.0 (13)
