### ISSUE TITLE
Sharing the app sends an invalid link 

### ISSUE THREAD

**Issue by fraziercarr** [soundscape-community/soundscape#59]
**Build:** 1.0.0 (10)

**Repro Steps:**

1. Launch Soundscape
2. Open the menu
3. Select 'Share'
4. Share to another phone or copy the message in to your notes app
5. Open the link

OR

1. Delete and reinstall Soundscape
2. Kill and relaunch the app repeatedly
3. On the 5th launch, select "share" on the modal
4. Share to another phone or copy the message in to your notes app
5. Open the link

**Expected Results:**
Ideal: The link will take you to Soundscape on the App Store  
If that's no possible because we don't have an App Store link until we launch: The link will take you to the website 

**Actual Results:**
The App Store opens but there's an error saying the app can't be found 

![IMG_8387](https://github.com/soundscape-community/soundscape/assets/13348113/6fcc30a4-169b-4f1b-8d4c-8d640a27fef2)

![IMG_8388](https://github.com/soundscape-community/soundscape/assets/13348113/aa71a7da-42a8-4931-b56c-3d824fbeba7b)

**Comment by steinbro** [comment]
It should be possible to determine the future app store URL before launch. Per https://developer.apple.com/forums/thread/127195 , that URL for us should be:

https://apps.apple.com/app/id6449701760

**Comment by steinbro** [comment]
Ah, it looks like @Oliver2213 already fixed that app store ID in commit a7f82010. So I'd expect the current app store link should work after launch.

**Comment by fraziercarr** [comment]
Excellent, thanks for confirming!
