### ISSUE TITLE
Soundscape community support link in app points to invalid Discord link 

### ISSUE THREAD

**Issue by LegendusMaximus** [soundscape-community/soundscape#60]
**Steps to reproduce:**
1. Open the app.
2. Open the menu and select "Help and tutorials"
3. Select the Soundscape community support button at the bottom, and you'll be taken to an invalid Discord page.
Do you think we should update this to a link to somewhere on the website?

**Comment by 2kai2kai2** [comment]
I believe has since been resolved by this commit
https://github.com/soundscape-community/soundscape/commit/bb67e4a6db5efa9272231536c79d9abb2db02fa2
It seems to work on my phone.
Issue needs to be closed.

**Comment by steinbro** [comment]
Thanks for flagging!
