### ISSUE TITLE
APPLE MAPS: Opening in Apple Maps doesn't place a pin on the location 

### ISSUE THREAD

**Issue by fraziercarr** [soundscape-community/soundscape#62]
**Build:** 1.0.0 (13)

**Device info:**

- iPhone 14 Pro
- iOS 16.6

**Repro Steps:**

1. Select Places Nearby > All Places
2. Select a POI from the list
3. Select the 'open in maps' button on the map (second in from the right on the map)
4. Select 'Apple Maps'

**Expected Result:**
Apple Maps will open with a pin on the map at the location of that POI and you will be able to navigate to it. This is how it works with the Google Maps option.

**Actual Results:**
Apple Maps opens and is centred on the location of the POI, but there is no pin on the map sp it is not possible to select to navigate to it.

**Comment by steinbro** [comment]
This should be fixed by #63 but should be validated in an upcoming build.

**Comment by steinbro** [comment]
Awaiting verification of fix in 1.0.1 test build.

**Comment by fraziercarr** [comment]
Tested and verified in build 1.0.1. Closing.
