### ISSUE TITLE
Audio beacon 15m cut-off

### ISSUE THREAD

**Issue by jchudge** [soundscape-community/soundscape#78]
Allow the user to configure the current setting of 15 metres for turning off the audio beacon. This distance was set in the original Soundscape and took into account the general level of accuracy experienced with GPS behaviour. However, based on user feedback, having the beacon turn off automatically can lead to frustration  - hence the requirement to make it configurable by the user. This could be done via 5 metre increments or less.

**Comment by steinbro** [comment]
I believe this is currently hard-coded as the constant `EnterImmediateVicinityDistance` at https://github.com/soundscape-community/soundscape/blob/main/apps/ios/GuideDogs/Code/Data/Destination%20Manager/DestinationManager.swift#L29.

**Comment by steinbro** [comment]
Also, the above constant may be shared among all functionality that uses geofencing, some proximity radius around a point that triggers some behavior when a user enters or leaves. I'm not sure what features beyond beacons this would affect, possibly route waypoints? Do we want this setting to change this proximity threshold across the app, or just beacons?
