### ISSUE TITLE
Marker’s file

### ISSUE THREAD

**Issue by Salma1004-code** [soundscape-community/soundscape#86]
I need to know where is the file in which the markers that can be specified by the user are stored. I need to set some locations as default for more than one instance of the application before launching them.

**Comment by steinbro** [comment]
Markers are stored in a Realm database. I don't believe this can be prepopulated in a specific installation. However, you can use the sharing feature in the app to create links that users can open to import markers and routes.

**Comment by steinbro** [comment]
Closing as this isn't a bug or feature request.
